task N1
VMezheynikov/reactJS_public pull request #1
Opened 2020-10-13 12:21 UTC by VMezheynikov

2020-10-14 07:10 UTC, dima19972525 commented
![image](https://user-images.githubusercontent.com/23092460/95955362-64945480-0e05-11eb-845a-532a47c6dd69.png)
Перемистите контент папки test-app в рут директорию, саму папку удалите

2020-10-14 07:14 UTC, dima19972525 commented
Приложение не запускается, вы удалили папку public (может, еще что)
![image](https://user-images.githubusercontent.com/23092460/95955719-f56b3000-0e05-11eb-87b7-e2047602d1ab.png)

2020-10-14 07:17 UTC, dima19972525 requested changes
поправьте изменения

2020-10-14 07:17 UTC, dima19972525 commented on test-app/src/App.css
> +.App-logo {
не уверен для чего этот класс (т.к. приложение не запустилось), скорее всего, он не нужен, я не нашел элемента с таким классом

2020-10-14 07:17 UTC, dima19972525 commented on test-app/src/App.js
> +import Card from './Card/Card';
Измените
```js
import Card from './Card/Card';
```
на
```js
import Card from './Card';
```
Чтобы так сделать, измените Card.js на index.js

2020-10-14 07:17 UTC, dima19972525 commented on test-app/src/Card/Card.js
> +const card = (props) => {
Компоненты пишите с большой буквы card -> Card

2020-10-15 06:58 UTC, VMezheynikov commented on test-app/src/Card/Card.js
> +const card = (props) => {
пока по курсу была информация про два вида обьявлений компонентов (классы и функции)
я пробежал вперед немного, и только там дальше были рекомендации для функциональных компонентов обозначать их с большой буквы.
По index.js тоже пока материала не было

2020-10-15 07:47 UTC, dima19972525 commented on test-app/src/Card/Card.js
> +const card = (props) => {
Проблема в том, что если вы будите использовать компоненты с маленькой буквы (не в вашем случае, конечно), то они будут рендериться как html теги https://stackoverflow.com/questions/30373343/reactjs-component-names-must-begin-with-capital-letters .

По index.js ничего и не будет, это просто фича для более красивого импорта компонента. Я прикрепил ссылку на style-guide в первом уроке, там этот момент показан https://github.com/airbnb/javascript/tree/master/react

2020-10-15 07:56 UTC, dima19972525 commented
![image](https://user-images.githubusercontent.com/23092460/96093162-7abd1600-0ed4-11eb-87f5-04e9ed453576.png)
![image](https://user-images.githubusercontent.com/23092460/96093169-7e509d00-0ed4-11eb-82fa-9492fb94f9dc.png)
У вас используется разное количество пробелов в компонентах App и Card.
Разработчики стараются придерживаться только одного стиля (не только в пробелы, но и другое).
Есть инструменты, помогающие в этом. Все зависит от ide, которую вы используете.
Я работаю с vscode, там есть плагин prettier, он автоматически все правит за меня, можете установить его.
Вы также можете установить prettier как модуль в свой проект и он должен работать у вас, также как и плагин https://prettier.io/

2020-10-15 07:56 UTC, dima19972525 approved these changes
Поправьте изменения и мерж

2020-10-15 07:56 UTC, dima19972525 commented on src/App.js
> +import logo from './logo.svg';
он не ипользуется, можете его удалить

2020-10-15 07:56 UTC, dima19972525 commented on src/Card/Card.js
> +const card = (props) => {
поправьте имя сейчас (хоть рекомендации появяться только дальше в уроках)

2020-10-16 07:22 UTC, dima19972525 commented
(на всякий случай)
когда я пишу: поправьте имзенения и мерж.
После правок, вы можете пушить изменения в мастер и делать следущее задание
![image](https://user-images.githubusercontent.com/23092460/96225293-8e7e8000-0f99-11eb-9e71-2ef2b53c1932.png)

2020-10-16 07:31 UTC, merged